// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The application can use Supabase's transaction pooler, while Prisma
    // migration commands need a direct/session connection that supports the
    // advisory locks and session state used by migration administration.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
